spring:
  application:
    name: chat
  data:
    mongodb:
      host: localhost
      port: 27017
      database: magu
  graphql:
    graphiql:
      enabled: true
springdoc:
  swagger-ui:
    path: /docs
